Task 8
Yakdanol/Tbank-Java-Developer pull request #6
Opened 2024-10-22 21:41 UTC by Yakdanol

2024-10-23 21:02 UTC, Yakdanol commented
Вторая часть задания по многопоточности (для Kotlin)

2024-11-08 15:09 UTC, SHvatov requested changes
 @Yakdanol в целом все ОК, оставил пару минорных комментариев - поправь их и можно буде мерджить)

2024-11-08 15:09 UTC, SHvatov commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/utils/KudagoInitializer.java
> +        CompletableFuture.allOf(categoryFuture, locationFuture).join();
👍

2024-11-08 15:09 UTC, SHvatov commented on Homework/task5_6/src/main/resources/application.properties
> +# ?????????? ??????? ??? FixedThreadPool
?? ??? ???)))

2024-11-08 15:09 UTC, SHvatov commented on Homework/task7/src/main/java/org/yakdanol/task7/service/CurrencyService.java
> +    public CompletableFuture<Double> convertToRubleAsync(double amount, String currencyCode) {
`Double` -> `BigDecimal` - не хочется денюжки из-за плавающей точки терять)

2024-11-08 15:09 UTC, SHvatov commented on Homework/task8/src/main/java/org/yakdanol/task8/config/ThreadPoolConfig.java
> +public class ThreadPoolConfig {
Тут бинам стоит дать более конкретные названия, ибо что в спринге, что в других компонентах, которые приезжают с автоконфигами, может быть много +- аналогично названных пулов.

2024-11-08 15:09 UTC, SHvatov commented on Homework/task7/src/main/java/org/yakdanol/task7/service/CurrencyService.java
> +    public CompletableFuture<Double> convertToRubleAsync(double amount, String currencyCode) {
Стоит поправить везде, в том числе и в моделях

2024-11-08 15:09 UTC, SHvatov commented on Homework/task8/src/main/java/org/yakdanol/task8/util/DataFetcher.java
> +        StringBuilder urlBuilder = new StringBuilder("https://kudago.com/public-api/v1.4/events/?" );
Это в константу можно вынести

2024-11-08 15:09 UTC, SHvatov commented on Homework/task8/src/main/java/org/yakdanol/task8/util/DataFetcher.java
> +        StringBuilder urlBuilder = new StringBuilder("https://kudago.com/public-api/v1.4/events/?" );
Параметры запроса - тоже

2024-11-09 12:52 UTC, Yakdanol commented on Homework/task7/src/main/java/org/yakdanol/task7/service/CurrencyService.java
> +    public CompletableFuture<Double> convertToRubleAsync(double amount, String currencyCode) {
Спасибо за совет, исправил )

2024-11-09 13:57 UTC, Yakdanol commented on Homework/task8/src/main/java/org/yakdanol/task8/config/ThreadPoolConfig.java
> +public class ThreadPoolConfig {
Понятно, переименовал

2024-11-09 14:06 UTC, Yakdanol commented
> @Yakdanol в целом все ОК, оставил пару минорных комментариев - поправь их и можно буде мерджить)

Исправил мелкие недочеты )

2024-11-10 07:11 UTC, SHvatov approved these changes
@Yakdanol 👌, можно моржить)

2024-11-10 09:13 UTC, merged