Task 9
Yakdanol/Tbank-Java-Developer pull request #7
Opened 2024-10-28 18:33 UTC by Yakdanol

2024-11-08 15:25 UTC, SHvatov requested changes
@Yakdanol 👍, оставил пару комментариев - посмотри их)

2024-11-08 15:25 UTC, SHvatov commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/model/entity/Category.java
> +@NoArgsConstructor
Просто на почитать по теме использования ломбока вместе с гибером - https://thorben-janssen.com/lombok-hibernate-how-to-avoid-common-pitfalls/

2024-11-08 15:25 UTC, SHvatov commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/model/entity/Category.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
И по поводу генераторов тоже советую вот это почитать - https://stackoverflow.com/questions/17780394/hibernate-identity-vs-sequence-entity-identifier-generators. Если кратко, при выборе генератора в проде, стоит учитывать профиль нагрузки и специфику его реализации.

2024-11-08 15:25 UTC, SHvatov commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/model/repository/EventRepository.java
> +    static Specification<Event> buildEventSpecification(String name, Location location, Date fromDate, Date toDate) {
Давай вместо статика сделаем метод с default реализацией. А еще лучше - отдельный DAO класс. А то сейчас у тебя репозиторий отвечает и за получение данных из БД, так и за формирование спеки для запроса, чтобы кто-то другой этот запрос выполнил (это немного неочевидно))

2024-11-08 15:25 UTC, SHvatov commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/service/EventService.java
> +    @Transactional
👍

2024-11-08 15:25 UTC, SHvatov commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/service/EventService.java
> +        Date from = (fromDate != null) ? java.sql.Timestamp.valueOf(fromDate) : null;
Это стоит вынести в утильный метод

2024-11-08 15:25 UTC, SHvatov commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/service/EventService.java
> +    @Transactional
Но вообще транзакции стоит использовать, когда у тебя несколько атомарных операций необходимо объединить в одну атомарную с точки зрения БД операцию. То есть, к примеру, наличие транзакции тут и в методе delete, как по мне, избыточно.

2024-11-08 15:25 UTC, SHvatov commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/service/EventService.java
> +    @Transactional
Это так, на будущее)

2024-11-08 15:25 UTC, SHvatov commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/utils/KudagoInitializer.java
> +        while (retryCount < MAX_RETRIES && !success) {
Это бы тоже вынести в отдельный метод, ибо логика дублируется

2024-11-08 15:25 UTC, SHvatov commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/utils/KudagoInitializer.java
> +        while (retryCount < MAX_RETRIES && !success) {
И вот инициализацию бы обернуть в транзакцию, чтобы мы либо сохранили все записи, либо ничего не сохранили и на следующем старте начали бы процесс инициализации заново, не опасаясь проблем с дупликацией данных

2024-11-09 14:33 UTC, Yakdanol commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/model/entity/Category.java
> +@NoArgsConstructor
Спасибо за информацию

2024-11-09 14:57 UTC, Yakdanol commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/model/entity/Category.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Даже не знал об этом, спасибо огромное за столь важное уточнение!

2024-11-09 15:11 UTC, Yakdanol commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/service/EventService.java
> +    @Transactional
Хорошо, учту на будущее )

2024-11-09 15:40 UTC, Yakdanol commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/utils/KudagoInitializer.java
> +        while (retryCount < MAX_RETRIES && !success) {
Хорошо, исправил

2024-11-09 16:10 UTC, Yakdanol commented on Homework/task5_6/src/main/java/org/yakdanol/task5_6/model/repository/EventRepository.java
> +    static Specification<Event> buildEventSpecification(String name, Location location, Date fromDate, Date toDate) {
Исправил

2024-11-09 16:12 UTC, Yakdanol commented
> @Yakdanol 👍, оставил пару комментариев - посмотри их)

Исправил недочеты

2024-11-09 16:12 UTC, Yakdanol commented
Исправил недочеты

2024-11-10 07:12 UTC, SHvatov approved these changes
@Yakdanol 👍

2024-11-10 10:06 UTC, merged